#!/usr/bin/env python3
"""Generate the llama-arch runtime traits include from JSON config."""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = REPO_ROOT / "configs" / "llama-arch-runtime-traits.json"
OUTPUT_PATH = REPO_ROOT / "src" / "llama-arch-runtime-traits.inc"

BOOL_FIELDS = [
    "is_recurrent",
    "is_hybrid",
    "is_diffusion",
    "supports_sm_tensor",
    "uses_encoder_pass",
    "prefers_embedding_outputs",
    "uses_sliding_window_metadata",
    "uses_explicit_swa_pattern",
]

INT_FIELDS = [
    "default_full_attention_interval",
    "default_sliding_window_pattern",
]

ENUM_FIELDS = {
    "default_expert_gating_func": {
        "softmax": "LLAMA_EXPERT_GATING_FUNC_TYPE_SOFTMAX",
        "sigmoid": "LLAMA_EXPERT_GATING_FUNC_TYPE_SIGMOID",
        "softmax_weight": "LLAMA_EXPERT_GATING_FUNC_TYPE_SOFTMAX_WEIGHT",
    },
}

OPTIONAL_BOOL_FIELDS = [
    "default_expert_weights_norm",
]

ALLOWED_FIELDS = set(BOOL_FIELDS + INT_FIELDS + list(ENUM_FIELDS) + OPTIONAL_BOOL_FIELDS)


def _bool_literal(value: bool) -> str:
    return "true" if value else "false"


def _validate_bool(arch: str, field: str, value: object) -> bool:
    if not isinstance(value, bool):
        raise ValueError(f"{arch}.{field} must be a boolean")
    return value


def _validate_uint(arch: str, field: str, value: object) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or value < 0:
        raise ValueError(f"{arch}.{field} must be a non-negative integer")
    return value


def _validate_enum(arch: str, field: str, value: object) -> str:
    if not isinstance(value, str):
        raise ValueError(f"{arch}.{field} must be a string")

    enum_value = ENUM_FIELDS[field].get(value)
    if enum_value is None:
        choices = ", ".join(sorted(ENUM_FIELDS[field]))
        raise ValueError(f"{arch}.{field} must be one of: {choices}")

    return enum_value


def _load_traits() -> dict[str, dict[str, object]]:
    data = json.loads(INPUT_PATH.read_text(encoding="utf-8"))

    if data.get("version") != 1:
        raise ValueError(f"{INPUT_PATH} must declare version 1")

    traits = data.get("traits")
    if not isinstance(traits, dict):
        raise ValueError(f"{INPUT_PATH} must contain a 'traits' object")

    validated: dict[str, dict[str, object]] = {}
    for arch, raw_fields in sorted(traits.items()):
        if not isinstance(arch, str) or not arch.startswith("LLM_ARCH_"):
            raise ValueError(f"Invalid arch key: {arch!r}")
        if not isinstance(raw_fields, dict) or not raw_fields:
            raise ValueError(f"{arch} must map to a non-empty object")

        unknown_fields = sorted(set(raw_fields) - ALLOWED_FIELDS)
        if unknown_fields:
            raise ValueError(f"{arch} has unknown fields: {', '.join(unknown_fields)}")

        fields: dict[str, object] = {}

        for field in BOOL_FIELDS:
            if field in raw_fields:
                fields[field] = _validate_bool(arch, field, raw_fields[field])

        for field in INT_FIELDS:
            if field in raw_fields:
                fields[field] = _validate_uint(arch, field, raw_fields[field])

        for field in ENUM_FIELDS:
            if field in raw_fields:
                fields[field] = _validate_enum(arch, field, raw_fields[field])

        for field in OPTIONAL_BOOL_FIELDS:
            if field in raw_fields:
                fields[field] = _validate_bool(arch, field, raw_fields[field])

        validated[arch] = fields

    return validated


def _render_traits(traits: dict[str, dict[str, object]]) -> str:
    lines = [
        "// This file is generated by scripts/gen-llama-arch-runtime-traits.py",
        "// from configs/llama-arch-runtime-traits.json. Do not edit by hand.",
        "",
    ]

    for arch, fields in traits.items():
        lines.append(f"    {{ {arch}, []() {{")
        lines.append("        llm_arch_runtime_traits traits;")

        for field in BOOL_FIELDS:
            if field in fields:
                lines.append(f"        traits.{field} = {_bool_literal(fields[field])};")

        for field in INT_FIELDS:
            if field in fields:
                lines.append(f"        traits.{field} = {fields[field]}u;")

        for field in ENUM_FIELDS:
            if field in fields:
                lines.append(f"        traits.{field} = {fields[field]};")

        if "default_expert_weights_norm" in fields:
            lines.append("        traits.has_default_expert_weights_norm = true;")
            lines.append(
                "        traits.default_expert_weights_norm = "
                f"{_bool_literal(fields['default_expert_weights_norm'])};"
            )

        lines.append("        return traits;")
        lines.append("    }() },")

    return "\n".join(lines) + "\n"


def main() -> None:
    traits = _load_traits()
    OUTPUT_PATH.write_text(_render_traits(traits), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
